### PR TITLE
Improved CI

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
- Adapt test to ert-runner convention
- Update travis to use containers and [evm](https://github.com/rejeep/evm)
- Setup coverage with undercover

:smiley:

### CODE REVIEW

**Comment by kiwanami** [comment]
Thank you!
Because I'm not sure about testing on the Travis CI, I'd learn github CI from your code.

**Comment by AdrieanKhisbe** [comment]
:smiley: 

what do you mean by github Ci?

**Comment by kiwanami** [comment]
It means Travis CI for github repositories.
For me, writing correct some setting files is very complicated, 
because we need to coordinate many environment such as the Emacs versions, the runtime environment and tools on Travis CI.
However, I should learn it to continue development with many contributors and users.

**Comment by AdrieanKhisbe** [comment]
Indeed, in some context it takes several commit&push to get it right. (and waiting config to fail in between ^^)

**Pull request merged**
